version: "3"
services:
  db:
    image: mysql:5.7
    restart: on-failure:5
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: machine-learning-match
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  node:
    depends_on:
      - db
    build: .
    user: "node"
    environment:
      - NODE_ENV=production
    ports: 
      - "80:3000"
    volumes:
      - ./:/home/node/app
    command: npm start
    links:
      - db
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80 # (*)
    restart: on-failure:5
    environment:
        PMA_HOST: db