version: "3"
services:
  db:
    image: mysql:5.7
    restart: on-failure:5
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: dbname
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  node:
    depends_on:
      - db
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports: 
      - "80:3000"
    command: "npm start"
    links:
      - db
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80 # (*)
    restart: on-failure:5
    environment:
        PMA_HOST: db